### ISSUE TITLE
setting flex grow to 0 doesn't work

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-ordered-layout-flow#27] opened 2017-12-20 14:52 UTC
this is the code that is run:
`        if (flexGrow == 0) {
            for (Component component : components) {
                component.getElement().getStyle()
                        .remove(FLEX_GROW_CSS_PROPERTY);
            }
        }`
But the default flex-grow is 1 in CSS:
`#layout ::slotted(*) {
    flex: 1 1 auto;
}`

**Comment by tmattsso** [comment] 2017-12-20 15:01
Actually, the default should probably be growth:0 for both the layouts. the default of 1 in V8 meant a different thing, for flexboxes it breaks a lot of things.

**Comment by haiwan** [comment] 2018-01-24 13:44
This seems to be fixed? It works now for me

**Comment by denis-anisimov** [comment] 2018-02-27 09:06
I don't really understand the ticket because there is no expected behavior, current behavior and the only thing that I may get from here is some steps to reproduce: use `setFlexGrow()`  method for some layout.

It looks like the issue is about default `flex-grow` value in CSS ( which CSS, where it is?).
And in this case it may be should be ticket for the client-side web component ?

Anyway, as I understand the absence of the `flex` style should be the same as `style="flex-grow: 0;"`
and not the `style="flex-grow: 1;"`.
I can at least confirm that behavior: by default the style absence is the same as `style="flex-grow: 0;"`.
So I'm closing the issue.

**Closed by denis-anisimov** 2018-02-27 09:06 UTC
Labels: bug
